development:
      clients:
        default:
          database: match
          hosts:
            - localhost:27017

test:
      clients:
        default:
          database: match
          hosts:
            - localhost:27017